--- !ruby/object:UIHelper::UI 
header: ~ 
footer: ~ 
page_header: ~
page_footer: ~
navigation: 
  - !ruby/object:UIHelper::Menubar 
    name: Main 
    menus: 
    - !ruby/object:UIHelper::Menu 
      name: Combray
      items: !ruby/object:UIHelper::MenuItemsFromFilesFactory 
        base_filename: swann_pg
        directory: texts/combray
    - !ruby/object:UIHelper::Menu 
      name: Features
      items:
        -
          name: Journal
          href: user_journal_path(current_user.id)
        -
          name: Discussion Board
          href: user_discussion_path(current_user.id)