--- !ruby/object:UI
page_header: ~
page_footer: ~
navigation: 
- !ruby/object:Menubar 
  name: Main 
  menus:
  - !ruby/object:Menu 
    name: Combray
    items: 
    - !ruby/object:MenuItemsFromFilesFactory 
      base_filename: swann_pg
      directory: texts/combray
      item_class: PageMenuItem
  - !ruby/object:Menu 
    name: Services
    items:
    - name: Journal
      path: user_journals_path(current_user.id)
    - name: Discussion Board
      path: discussions_path
  - !ruby/object:Menu 
    name: My Account
    items:
    - name: Dashboard
      path: user_dashboard_path(current_user.id)
    - name: Sign Out
      path: signout_path