--- !ruby/object:UI
page_header: ~
page_footer: ~
navigation: 
- !ruby/object:Menubar 
  name: Main 
  menus:
  - !ruby/object:Menu 
    name: Inferno
    items: 
    - !ruby/object:MenuItemsFromFilesFactory 
      base_filename: inf_canto
      directory: texts/commedia/longfellow/inf
      item_class: CantoMenuItem
  - !ruby/object:Menu 
    name: Purgatorio
    items: 
    - !ruby/object:MenuItemsFromFilesFactory 
      base_filename: purg_canto
      directory: texts/commedia/longfellow/purg
      item_class: CantoMenuItem
  - !ruby/object:Menu 
    name: Paradiso
    items: 
    - !ruby/object:MenuItemsFromFilesFactory 
      base_filename: par_canto
      directory: texts/commedia/longfellow/par
      item_class: CantoMenuItem